# ここはお決まり  
AWSTemplateFormatVersion: "2010-09-09"  
# テンプレートについての説明  
Description: Create VPCandPublicSubnetandPrivateSubnet"
# ここから作成するリソースについての記述  
Resources:  
  VPC:  
    # リソースのタイプを指定  
    Type: AWS::EC2::VPC  
    # リソースのプロパティを指定  
    Properties:  
      # IPv4 CIDR  
      CidrBlock: 10.0.0.0/16  
    # Nameタグをつけてみた  
      Tags:  
        - Key: Name  
          Value: CloudFormationVPC  
        - Key: Creationdate
          Value: 20191215
    # Public Subnetを作成  
  PublicSubnet:  
    Type: "AWS::EC2::Subnet"  
    Properties:  
      VpcId: !Ref VPC  
      CidrBlock: "10.0.10.0/24"  
      AvailabilityZone: "ap-northeast-1a"  
      Tags:  
        - Key: "Name"  
          Value: "PublicSubnet"  
    # Private Subnetを作成  
  PrivateSubnet:  
    Type: "AWS::EC2::Subnet"  
    Properties:  
      VpcId: !Ref VPC  
      CidrBlock: "10.0.20.0/24"  
      AvailabilityZone: "ap-northeast-1a"  
      Tags:  
        - Key: "Name"  
          Value: "PrivateSubnet"  
    # InternetGatewayを作成  
  InternetGateway:  
    Type: "AWS::EC2::InternetGateway"  
    Properties:  
      Tags:  
        - Key: "Name"  
          Value: "CloudFormationInternetGateway"  
    # InternetGatewayをVPCにアタッチ  
  VPCGatewayAttachment:  
    Type: "AWS::EC2::VPCGatewayAttachment"  
    Properties:  
      InternetGatewayId: !Ref InternetGateway  
      VpcId: !Ref VPC  
    # Public Subnet用のルートテーブルを作成  
  PublicRouteTable:  
    Type: "AWS::EC2::RouteTable"  
    Properties:  
      VpcId: !Ref VPC  
      Tags:  
        - Key: "Name"  
          Value: "PublicRouteTable"  
  PublicRouting:  
    Type: "AWS::EC2::Route"   
    Properties:  
      RouteTableId: !Ref PublicRouteTable  
      GatewayId: !Ref InternetGateway  
      DestinationCidrBlock: "0.0.0.0/0"  
    # ルートテーブルをサブネットにアタッチ  
  PublicRouteTableAttachToPublicSubnetA:  
    Type: "AWS::EC2::SubnetRouteTableAssociation"  
    Properties:  
      RouteTableId: !Ref PublicRouteTable  
      SubnetId: !Ref PublicSubnet 
    # パブリックサブネット用セキュリティグループを作成  
  SecurityGroupForPublicSubnet:  
    Type: "AWS::EC2::SecurityGroup"  
    Properties:  
      GroupName: "SecurityGroupForPublicSubnet"  
      GroupDescription: "SecurityGroup For PublicSubnet"  
      SecurityGroupIngress:  
        - IpProtocol: "tcp"  
          FromPort: 22  
          ToPort: 22  
          CidrIp: "0.0.0.0/0"
        
        - IpProtocol: "tcp"  
          FromPort: 80  
          ToPort: 80 
          CidrIp: "0.0.0.0/0"

      VpcId: !Ref VPC 
  
  # パブリックサブネットにEC2を作成  
  EC2onPublicSubnet:  
    Type: "AWS::EC2::Instance"  
    Properties:  
      ImageId: "ami-068a6cefc24c301d2"  
      InstanceType: "t2.micro"  
      SubnetId: !Ref PublicSubnet  
      BlockDeviceMappings:  
        - DeviceName: "/dev/xvda"  
          Ebs:  
            VolumeType: "gp2"  
            VolumeSize: 8  
            DeleteOnTermination: true  
      SecurityGroupIds:  
        - !Ref SecurityGroupForPublicSubnet  
      #KeyName: "cloudformation"  
      Tags:  
        - Key: "Name"  
          Value: "PublicEC2"
          # ElasticIPを割り当て  
  ElasticIP:  
    Type: "AWS::EC2::EIP"  
    Properties:  
      Domain: !Ref VPC
      InstanceId: !Ref EC2onPublicSubnet    
